[package]
name = "WinApp"
version = "0.1.0"
authors = ["N4U"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[dependencies.winapi]
version = "0.3"
features = ["winuser"]
